Repository IBM/ibm-helm-repo-operator, pull requests merged in 2020-05, with the labels that each got.

#42 missing SHA fields in bundle CRD
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/XS

#43 37259: changes to address restricted scc
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/templates/rbac.yaml
  helm-charts/helm-repo/values-metadata.yaml
Labels: approved, lgtm, size/M

#44 37644: revert crd back to v1alpha1
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#45 Readme & CSV updates
  README.md
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#46 Cleanup to push case bundle through after changes to operator
  helm-charts/helm-repo/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-repo/values-metadata.yaml
Labels: approved, lgtm, size/M

#47 support operator upgrade from 3.3 to 3.4
  Makefile
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/templates/ingress-charts-rbac.yaml
  helm-charts/helm-repo/templates/ingress-helm-repo-open.yaml
  helm-charts/helm-repo/templates/ingress-index-open.yaml
  helm-charts/helm-repo/templates/ingress-v1-charts-rbac.yaml
  helm-charts/helm-repo/templates/ingress-v1-index-open.yaml
  helm-charts/helm-repo/templates/rbac.yaml
  helm-charts/helm-repo/templates/service.yaml
  helm-charts/helm-repo/values-metadata.yaml
  helm-charts/helm-repo/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#49 increase memory allocation to operator pod
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#50 37376: Update Helm foundation operators description and documentation
  README.md
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#51 37933: Helm foundation: Update productVersion metering annotations to…
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/templates/deployment.yaml
Labels: approved, lgtm

#52 remove image setting from helm repo
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/S

#53 change instance name to match operand
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/S

#54 37961: disable audit logging by default
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values.yaml
  watches.yaml
Labels: approved, lgtm, size/M

#55 38052: Creating beta channel for cloud pak usage
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#56 38081: local-charts is not working on CS 3.4
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.1/ibm-helm-repo-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.1/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  helm-charts/helm-repo/Chart.yaml
  helm-charts/helm-repo/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values-metadata.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/XL

#57 38148: Helm repo operator CSV name conflict
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.1/ibm-helm-repo-operator.v3.6.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#58 add common scripts protect-csv and bump-up-csv
  .githooks/pre-commit
  Makefile
  commonUtil/scripts/bump-up-csv.sh
  commonUtil/scripts/protect-csv.sh
  commonUtil/scripts/push-csv.sh
Labels: approved, lgtm, size/L

#60 update operator image to use latest tag
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.1/ibm-helm-repo-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#61 38341: Helm Foundation - Move CS 3.4.1 into beta channel
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.1/ibm-helm-repo-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
