Repository IBM/ibm-helm-repo-operator, pull requests merged in 2020-03, with the labels that each got.

#4 fixes to get helm repo pod running
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  commonUtil/resources/opencloud-operators.yaml
  commonUtil/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/0.0.1/ibm-helm-repo-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  helm-charts/helm-repo/README.md
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/templates/rbac.yaml
  helm-charts/helm-repo/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#6 fix helm-repo vascan vulnerability issue
  build/Dockerfile
  build/Dockerfile.ppc64le
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/0.0.1/ibm-helm-repo-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/helm-repo/README.md
  helm-charts/helm-repo/templates/_helpers.tpl
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/M

#7 add metering and healthcheck annotations
  commonUtil/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/0.0.1/ibm-helm-repo-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/templates/deployment.yaml
Labels: approved, lgtm, size/S

#8 update csv version to 3.5.0
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/generate-scorecard.sh
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/L

#9 change current csv to 3.5.0
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#10 add labels and license to docker files to pass image scan
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/M

#12 update healthcheck dependencies annotation
  helm-charts/helm-repo/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#13 fixed missing args in Dockerfile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/S

#14 update csv metadata fields
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#15 clean up for RH certification
  Makefile
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/templates/rbac.yaml
Labels: approved, lgtm, size/L

#16 add ReplicaSet in resources list
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#17 fixed wrong version for containerImage annotation
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#18 update icp-audit-service to 3.4.0
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/XS

#19 add README.md
  README.md
  SECURITY_CONTACTS
Labels: approved, lgtm, size/M
