Repository IBM/ibm-helm-repo-operator, pull requests merged in 2020-04, with the labels that each got.

#20 fixed push-multi-arch target to push with git commit tag
  .gitignore
  Makefile
Labels: approved, lgtm, size/XS

#21 flesh out validation definition
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/L

#22 remove type: object from status subresource
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/XS

#23 Bluzarraga patch 1
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/XS

#25 update operator version to 3.6.0
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#26 include spec.replaces as with the other operators
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#27 update 3.6.0 csv and crd
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/L

#28 make resource requests equal limits to avoid OOM
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/S

#29 separate registry from image name for cicd blocker
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  helm-charts/helm-repo/Chart.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/M

#30 audit service has new requirements
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/S

#31 36969: add operator dependencies
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#32 add dev channel
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
Labels: approved, lgtm, size/XS

#33 37228: remove unnecessarily exposed configurations
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1_helmrepo_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  helm-charts/helm-repo/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#34 fixes to prepare for integration build
  Makefile
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#35 merge master changes into dev branch to resolve API version issue
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1_helmrepo_cr.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, size/S

#36 travis build troubleshooting for the case bundle
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/values-metadata.yaml
Labels: approved, lgtm, size/L

#37 Had to clean up a few things
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values-metadata.yaml
Labels: approved, lgtm, size/M

#38 37566: Canary Failure: helm-repo pod is unschedulable
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values-metadata.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/M

#39 fix broken crd
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/operator.ibm.com_helmrepos_crd.yaml
Labels: approved, lgtm, size/S

#40 37408: Remediate package vulnerability
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#41 use image digest instead of tag
  deploy/crds/operator.ibm.com_helmrepos_crd.yaml
  deploy/crds/operator.ibm.com_v1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.0/ibm-helm-repo-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/helm-repo/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-repo/ibm_cloud_pak/qualification.yaml
  helm-charts/helm-repo/templates/deployment.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/M
