Repository IBM/ibm-helm-repo-operator, pull requests merged in 2020-08, with the labels that each got.

#68 bump up CSV to 3.6.3
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/config_docker.sh
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.3/ibm-helm-repo-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.3/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/Chart.yaml
Labels: approved, lgtm, size/XL

#69 40023 - downgrade manifest-tool to v0.7.0
  Makefile
Labels: approved, lgtm, size/XS

#71 removed productVersion annotation
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.3/ibm-helm-repo-operator.v3.6.3.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#72 improve dev workflow
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.3/ibm-helm-repo-operator.v3.6.3.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
  helm-charts/helm-repo/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/M

#73 fix audit image
  hack/csv_images.sed
Labels: approved, lgtm, size/XS

#74 40210: add pod anit-affinity for HA support
  helm-charts/helm-repo/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#75 40265 - update icp-audit-service image
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.3/ibm-helm-repo-operator.v3.6.3.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-repo/values.yaml
Labels: approved, lgtm, size/XS

#76 updated operator to v3.6.4
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.4/ibm-helm-repo-operator.v3.6.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.4/operator.ibm.com_helmrepos_crd.yaml
  deploy/olm-catalog/ibm-helm-repo-operator/ibm-helm-repo-operator.package.yaml
  helm-charts/helm-repo/Chart.yaml
Labels: approved, lgtm, size/XL

#77 added multi-arch support labels
  deploy/olm-catalog/ibm-helm-repo-operator/3.6.4/ibm-helm-repo-operator.v3.6.4.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#78 40594: Canary Failure: helm-repo and catalog-ui not running on OCP 4.6
  helm-charts/helm-repo/Chart.yaml
Labels: approved, lgtm, size/XS
